name: Publish to GitHub Packages

on:
  release:
    types: [ created ]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: liberica
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - run: ./gradlew :api:build
      - run: ./gradlew :api:publish
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The PGP private key must DO NOT contain BEGIN/END markers to be
          # successfully applied by `useInMemoryPgpKeys(...)` signing method.
          # @See api/gradle.build.kts#signing
          GPG_PRIVATE_KEY: ${{ secrets.GRADLE_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
